name: "CI"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  terraform:
    name: "CI"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
      - run: ansible-galaxy install -r ./step_0/requirements.yml
      - uses: pre-commit/action@v3.0.0
