name: "CI"

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "CI"
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/platform-engineering-org/helper:latest@sha256:6f3ef865b026d7f51cb58186a40abe20c0026fa52e14105cd635ea87b48b58ed

    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup ASDF environment
        run: |
          ASDF_DIR=/root/.asdf
          echo "ASDF_DIR=$ASDF_DIR" >> $GITHUB_ENV
          echo "ASDF_DATA_DIR=$ASDF_DIR" >> $GITHUB_ENV
          echo "$ASDF_DIR/bin" >> $GITHUB_PATH
          echo "$ASDF_DIR/shims" >> $GITHUB_PATH
          $ASDF_DIR/bin/asdf reshim
          cp /root/.tool-versions ~/
      - run: git config --global --add safe.directory '*'
      - uses: pre-commit/action@v3.0.0
      - name: Show pre-commit log
        if: ${{ failure() }}
        run: |
          cat /github/home/.cache/pre-commit/pre-commit.log
