name: "CI"

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "CI"
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/platform-engineering-org/helper:latest

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-python@v4.6.0
      - name: Setup ASDF environment
        run: |
          ASDF_DIR=/root/.asdf
          echo "ASDF_DIR=$ASDF_DIR" >> $GITHUB_ENV
          echo "ASDF_DATA_DIR=$ASDF_DIR" >> $GITHUB_ENV
          echo "$ASDF_DIR/bin" >> $GITHUB_PATH
          echo "$ASDF_DIR/shims" >> $GITHUB_PATH
          $ASDF_DIR/bin/asdf reshim
          cp /root/.tool-versions ~/
      - run: |
          pip install pre-commit==3.3.1
          dnf install -y git
          pre-commit run --show-diff-on-failure --color=always --all-files
