name: "CI"

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "CI"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
      - uses: pre-commit/action@v3.0.0
