name: "DEPLOYMENT"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "DEPLOYMENT"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - uses: eLco/setup-terragrunt@v1.0.2
        with:
          terragrunt_version: 0.43.0

      - name: Plan
        run: make ENV=prod plan-in-container
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-2

      - name: Deploy
        run: make ENV=prod up-in-container
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-2
